//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BimSpeedModelFromCad.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BimSpeedModelFromCad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE COLUMN FROM AUTOCAD FILE.
        /// </summary>
        public static string COLUMN_FROM_CAD_VIEW_TITLE {
            get {
                return ResourceManager.GetString("COLUMN_FROM_CAD_VIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string COMMON_AREA {
            get {
                return ResourceManager.GetString("COMMON_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Level :.
        /// </summary>
        public static string COMMON_BASELEVEL {
            get {
                return ResourceManager.GetString("COMMON_BASELEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Offset :.
        /// </summary>
        public static string COMMON_BASEOFFSET {
            get {
                return ResourceManager.GetString("COMMON_BASEOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string COMMON_CLOSE {
            get {
                return ResourceManager.GetString("COMMON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string COMMON_CREATE {
            get {
                return ResourceManager.GetString("COMMON_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept :.
        /// </summary>
        public static string COMMON_DEPT {
            get {
                return ResourceManager.GetString("COMMON_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edges number.
        /// </summary>
        public static string COMMON_EDGENUMBER {
            get {
                return ResourceManager.GetString("COMMON_EDGENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family :.
        /// </summary>
        public static string COMMON_FAMILY {
            get {
                return ResourceManager.GetString("COMMON_FAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor type:.
        /// </summary>
        public static string COMMON_FLOORTYPE {
            get {
                return ResourceManager.GetString("COMMON_FLOORTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid types :.
        /// </summary>
        public static string COMMON_GRIDTYPES {
            get {
                return ResourceManager.GetString("COMMON_GRIDTYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string COMMON_HEIGHT {
            get {
                return ResourceManager.GetString("COMMON_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height :.
        /// </summary>
        public static string COMMON_HEIGHTFAMILY {
            get {
                return ResourceManager.GetString("COMMON_HEIGHTFAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsColumn.
        /// </summary>
        public static string COMMON_ISCOLUMN {
            get {
                return ResourceManager.GetString("COMMON_ISCOLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length .
        /// </summary>
        public static string COMMON_LENGTH {
            get {
                return ResourceManager.GetString("COMMON_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level :.
        /// </summary>
        public static string COMMON_LEVEL {
            get {
                return ResourceManager.GetString("COMMON_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string COMMON_MARK {
            get {
                return ResourceManager.GetString("COMMON_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You canceled the pick.
        /// </summary>
        public static string COMMON_MESSAGEPICKPOINTCAD {
            get {
                return ResourceManager.GetString("COMMON_MESSAGEPICKPOINTCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected coordinates in revit please choose again.
        /// </summary>
        public static string COMMON_MESSAGEPICKPOINTREVIT {
            get {
                return ResourceManager.GetString("COMMON_MESSAGEPICKPOINTREVIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not select any elements.
        /// </summary>
        public static string COMMON_MESSAGESELECTELEMENTCAD {
            get {
                return ResourceManager.GetString("COMMON_MESSAGESELECTELEMENTCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        public static string COMMON_NOTIFY {
            get {
                return ResourceManager.GetString("COMMON_NOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string COMMON_NUMBER {
            get {
                return ResourceManager.GetString("COMMON_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset from level  : .
        /// </summary>
        public static string COMMON_OFFSETFROMLEVEL {
            get {
                return ResourceManager.GetString("COMMON_OFFSETFROMLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string COMMON_OK {
            get {
                return ResourceManager.GetString("COMMON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius .
        /// </summary>
        public static string COMMON_RADIUS {
            get {
                return ResourceManager.GetString("COMMON_RADIUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from cad.
        /// </summary>
        public static string COMMON_SELECTFROMCAD {
            get {
                return ResourceManager.GetString("COMMON_SELECTFROMCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slab type:.
        /// </summary>
        public static string COMMON_SLABRYPE {
            get {
                return ResourceManager.GetString("COMMON_SLABRYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string COMMON_TEXT {
            get {
                return ResourceManager.GetString("COMMON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness :.
        /// </summary>
        public static string COMMON_THICKNESS {
            get {
                return ResourceManager.GetString("COMMON_THICKNESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Level :.
        /// </summary>
        public static string COMMON_TOPLEVEL {
            get {
                return ResourceManager.GetString("COMMON_TOPLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Offset :.
        /// </summary>
        public static string COMMON_TOPOFFSET {
            get {
                return ResourceManager.GetString("COMMON_TOPOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string COMMON_WIDTH {
            get {
                return ResourceManager.GetString("COMMON_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width : .
        /// </summary>
        public static string COMMON_WITDHFAMILY {
            get {
                return ResourceManager.GetString("COMMON_WITDHFAMILY", resourceCulture);
            }
        }
    }
}
